### ISSUE TITLE
Feature Request: Open the raw markdown task file with default editor

### ISSUE THREAD

**Issue by bandithijo** [smallhadroncollider/taskell#103] opened 2021-07-09 07:00 UTC
Hi, @smallhadroncollider

Is there any chance to add feature like "Edit a markdown task via the default editor" with keybind or command `:`.
I found this feature available in vit (Visual Interactive Taskwarrior).
I think it will be very helpful if this feature is available ini taskell.

Thank you for your hard work.

Regards,
(^_^)

**Comment by smallhadroncollider** [comment] 2021-07-09 08:24
I think this is a duplicate of https://github.com/smallhadroncollider/taskell/issues/91?

**Comment by bandithijo** [comment] 2021-07-09 08:30
> I think this is a duplicate of #91?

Ah, yeah, you're right. It's so close.
I apologize for my mistake not checking the list of issues more broadly.

**Closed** 2021-07-09 08:30 UTC

**Comment by smallhadroncollider** [comment] 2021-07-09 08:42
No worries.
